server:
  port: 8088

spring:
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 853211
      hikari:
        connection-timeout: 30000
        minimum-idle: 5
        maximum-pool-size: 20
        auto-commit: true
        idle-timeout: 600000
        pool-name: DateSourceHikariCP
        max-lifetime: 1800000
        connection-test-query: select 1


mybatis-plus:
  type-aliases-package: com.crossyf.entity
  mapper-locations: classpath:mapper/*.xml

